complete -c netinfo -l json -d "Output machine-readable JSON"
complete -c netinfo -l sweep -d "Perform 64-worker parallel ping sweep"
complete -c netinfo -l vendors -d "Lookup MAC OUI vendors online"
complete -c netinfo -l no-dns -d "Skip reverse-DNS hostname resolution"
complete -c netinfo -l no-color -d "Disable ANSI color output"
complete -c netinfo -l save -r -d "Save report snapshot to JSON file"
complete -c netinfo -l compare -r -d "Compare report against a saved snapshot file"
complete -c netinfo -l version -d "Display version"
complete -c netinfo -l help -d "Display help"
